%generate comaprison plot
clear all
% load the data from excel sheet
load('psnrtimevsMSE')
figure

plot(SMSE,Spsnrtime(:,1),':ko','LineWidth',1,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',6)
hold
plot(SMSE,Spsnrtime(:,2),':ks','LineWidth',1,...
                'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',6)
plot(SMSE,Spsnrtime(:,3),':k^','LineWidth',1,...
                'MarkerEdgeColor','b',...
                'MarkerFaceColor','b',...
                'MarkerSize',6)
plot(SMSE,Spsnrtime(:,4),':kd','LineWidth',1,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',6)
 axis([1.1 1.5  0  45])           
 h = legend('Adaptive CS','Intraframe TV','Differencing Algo','Block CS',2);
 set(h,'Interpreter','none');
 
 % Create xlabel
xlabel({'Temporal change'});

% Create ylabel
ylabel({'PSNR/time'});

% Create legend

set(h,'Interpreter','none','Position',[0.5878 0.694 0.2768 0.1889]);

figure

plot(RMSE,Rpsnrtime(:,1),':ko','LineWidth',1,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',6)
hold
plot(RMSE,Rpsnrtime(:,2),':ks','LineWidth',1,...
                'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',6)
plot(RMSE,Rpsnrtime(:,3),':k^','LineWidth',1,...
                'MarkerEdgeColor','b',...
                'MarkerFaceColor','b',...
                'MarkerSize',6)
plot(RMSE,Rpsnrtime(:,4),':kd','LineWidth',1,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',6)
 h = legend('Adaptive CS','Intraframe TV','Differencing Algo','Block CS',2);
 set(h,'Interpreter','none');
 
 % Create xlabel
xlabel({'Temporal change'});

% Create ylabel
ylabel({'PSNR/time'});

% Create legend

set(h,'Interpreter','none','Position',[0.5878 0.694 0.2768 0.1889]);

